---
# tasks file for freeradius (Debian specifc)

- name: Install FreeRADIUS packages (Debian)
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ freeradius_packages }}"
  tags:
    - freeradius
