---
# tasks file for freeradius

- name: Include distribution specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - freeradius

- include: RedHat.yml
  when: ansible_os_family == "RedHat"
  tags:
    - freeradius

- include: Ubuntu.yml
  when: ansible_os_family == "Ubuntu"
  tags:
    - freeradius

#- name: Create radiusd configuration file
#  become: yes
#  template:
#    src: radiusd.conf.j2
#    dest: /etc/freeradius/radiusd.conf
#    owner: root
#    group: freerad
#    mode: 0640
#  notify:
#    - reload freeradius
#  tags:
#    - freeradius

- name: Ensure FreeRADIUS service is started and enabled on boot
  become: yes
  service:
    name: "{{ freeradius_service_name }}"
    state: started
    enabled: yes
  tags:
    - freeradius
