---
# tasks file for freeradius (RedHat specific)

- name: Install FreeRADIUS packages
  become: yes
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ freeradius_packages }}"
  tags:
    - freeradius
